In [1]:
# Import dependencies
import pandas as pd
from sqlalchemy import create_engine

In [2]:
# Import first csv file
csv_file = "US_Videos.csv"
us_videos_df = pd.read_csv(csv_file)
us_videos_df.head()

,Unnamed: 0,video_id,title,publishedAt,channelId,channelTitle,categoryId,trending_date,tags,view_count,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,description
0,0,IhO1FcjDMV4,Meatpacking: Last Week Tonight with John Olive...,2021-02-22T07:30:01Z,UC3XTzVzaHQEd30rQbuvCtTQ,LastWeekTonight,24,21.22.02,[none],1067147,60111,1221,6866,https://i.ytimg.com/vi/IhO1FcjDMV4/default.jpg,False,False,The pandemic has thrown into high relief some ...
1,1,p4Wy84AOzj0,"Best 3D Pen Art Wins $5,000 Challenge! | ZHC C...",2021-02-21T20:43:28Z,UCPAk4rqVIwg1NCXh61VJxbg,ZHC Crafts,26,21.22.02,[none],1047854,50662,690,4879,https://i.ytimg.com/vi/p4Wy84AOzj0/default.jpg,False,False,I can't believe we made art using 3d pens and ...
2,2,4eKXwKDdXYA,100 Days - [Minecraft Superflat],2021-02-20T18:00:01Z,UC9FkeEFIGd9FXRfxpTltXYA,Luke TheNotable,20,21.22.02,luke thenotable|luke|the|notable|luke thenotab...,6133266,372753,7961,39551,https://i.ytimg.com/vi/4eKXwKDdXYA/default.jpg,False,False,This video is intended for audiences 13+ years...
3,3,XHR5mt2gBjo,Amazing! Luke Bryan Calls 15-Year-Old Casey Bi...,2021-02-22T01:53:12Z,UCAMPco9PqjBbI_MLsDOO4Jw,American Idol,24,21.22.02,American Idol|singing competition|Katy Perry|R...,790238,14267,129,1257,https://i.ytimg.com/vi/XHR5mt2gBjo/default.jpg,False,False,Small but MIGHTY! Casey Bishop completely blow...
4,4,C-icyHEb7W4,Game Theory: Did Reddit Just SOLVE FNAF?,2021-02-20T19:05:26Z,UCo_IB5145EVNcf8hw1Kku7w,The Game Theorists,20,21.22.02,fnaf|five nights at freddy's|fnaf 4|fnaf theor...,3248661,225780,2872,31885,https://i.ytimg.com/vi/C-icyHEb7W4/default.jpg,False,False,Get Yourself Some BRAND NEW Theory Wear! ► htt...

In [3]:
# Import second csv file
csv_file = "Youtube_Dataset.csv"
youtube_df = pd.read_csv(csv_file)
youtube_df.head()

,Video Name,Channel Name,Comment Id,User Name,Comment,Date,Likes
0,Luis Fonsi - Despacito ft. Daddy Yankee,LuisFonsiVEVO,UgwV0tapZzaFxdYm1z14AaABAg,GAMIT yuvraj,The people who liked this comment is officiall...,2020-08-10T20:00:43Z,98280
1,Luis Fonsi - Despacito ft. Daddy Yankee,LuisFonsiVEVO,UgyiccblP3A16aixpit4AaABAg,MrCrazy,"- Wait, it's 7B views\n- Always has been",2020-09-07T20:52:36Z,773
2,Luis Fonsi - Despacito ft. Daddy Yankee,LuisFonsiVEVO,Ugx7THW3EBNJlhJuwSB4AaABAg,60K Subs With 1 Video Challenge,*Teacher: What is the population of the Earth?...,2019-11-21T03:23:32Z,356081
3,Luis Fonsi - Despacito ft. Daddy Yankee,LuisFonsiVEVO,UgzXUsI6yrRjTKNASf94AaABAg,Srivathsa D,Let's be honest this wasn't your recommendatio...,2020-09-09T03:41:34Z,13
4,Luis Fonsi - Despacito ft. Daddy Yankee,LuisFonsiVEVO,UgxCu6mywg6uqjueHQ14AaABAg,1k Subscribers Challenge Without Any Video,Types Of People:\n10% Enjoying Song \n90% Chec...,2020-09-08T09:53:24Z,122

In [4]:
# Clean up the identify the columns we want from first csv
us_videos_df = us_videos_df[["title", "likes"]].copy()
us_videos_df.head()

                                               title   likes
0  Meatpacking: Last Week Tonight with John Olive...   60111
1  Best 3D Pen Art Wins $5,000 Challenge! | ZHC C...   50662
2                   100 Days - [Minecraft Superflat]  372753
3  Amazing! Luke Bryan Calls 15-Year-Old Casey Bi...   14267
4           Game Theory: Did Reddit Just SOLVE FNAF?  225780

In [5]:
# Clean up the identify the columns we want from second csv
youtube_df = youtube_df[["Video Name", "Likes"]].copy()
youtube_df.head()

                                Video Name   Likes
0  Luis Fonsi - Despacito ft. Daddy Yankee   98280
1  Luis Fonsi - Despacito ft. Daddy Yankee     773
2  Luis Fonsi - Despacito ft. Daddy Yankee  356081
3  Luis Fonsi - Despacito ft. Daddy Yankee      13
4  Luis Fonsi - Despacito ft. Daddy Yankee     122

In [6]:
# Change the cloumn name of Video Name
youtube_df = youtube_df.rename(columns={"Video Name": "video_name", "Likes": "likes"})
youtube_df

                                     video_name   likes
0       Luis Fonsi - Despacito ft. Daddy Yankee   98280
1       Luis Fonsi - Despacito ft. Daddy Yankee     773
2       Luis Fonsi - Despacito ft. Daddy Yankee  356081
3       Luis Fonsi - Despacito ft. Daddy Yankee      13
4       Luis Fonsi - Despacito ft. Daddy Yankee     122
...                                         ...     ...
19295  ZAYN - PILLOWTALK (Official Music Video)    5087
19296  ZAYN - PILLOWTALK (Official Music Video)       6
19297  ZAYN - PILLOWTALK (Official Music Video)       5
19298  ZAYN - PILLOWTALK (Official Music Video)       4
19299  ZAYN - PILLOWTALK (Official Music Video)       3

[19300 rows x 2 columns]

In [7]:
# Connect to local database
rds_connection_string = "postgres:postgres@localhost:5432/youtube_db"
engine = create_engine(f'postgresql://{rds_connection_string}')

In [8]:
# Use pandas to load first csv converted DataFrame into database
us_videos_df.to_sql(name='videos', con=engine, if_exists='append', index=False)

In [9]:
# Use pandas to load second csv converted first DataFrame into database
youtube_df.to_sql(name='youtube', con=engine, if_exists='append', index=False)